apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apache-ro
  namespace: apache
spec:
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4.55
        imagePullPolicy: Always
  selector:
    matchLabels:
      app: apache
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 50
      # The following pause step will pause the rollout indefinitely until manually resumed.
      # Rollouts can be manually resumed by running `kubectl argo rollouts promote ROLLOUT`
      - pause: {}
      - setWeight: 40
      - pause: {duration: 40s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}
